# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  miamirising.org:
    site_hosts:
      - canonical: miamirising.pix
        redirects:
          - www.miamirising.pix
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: developers@tinypixel.io
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    php_memory_limit: 512M
